[project]
name = "ambedkargpt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pdfminer-six>=20251107",
    "pypdf>=6.4.1",
    "setuptools>=80.9.0",
    "spacy>=3.8.11",
    "wheel>=0.45.1",
]
